[package]
name = "crispen-ocio"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }

[build-dependencies]
cc = "1.2"
cmake = "0.1"
pkg-config = "0.3"

[lints]
workspace = true
