[package]
name = "crispen-demo"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
crispen-core = { path = "../crispen-core" }
crispen-bevy = { path = "../crispen-bevy" }
bevy = { workspace = true, features = [
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_asset",
    "bevy_log",
    "bevy_ui",
    "bevy_winit",
    "wayland",
    "x11",
] }
serde = { workspace = true }
serde_json = { workspace = true }
wry = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
futures-util = { workspace = true }
tracing = { workspace = true }
image = { workspace = true }

[lints]
workspace = true
