[package]
name = "crispen-oiio"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
crispen-core = { path = "../crispen-core" }
thiserror = { workspace = true }

[build-dependencies]
cc = "1.2"
cmake = "0.1"
pkg-config = "0.3"

[lints]
workspace = true
